stages:
  download_hui_data:
    foreach: ${speaker}
    do:
      cmd: python src/prepare_hui_data.py --speaker ${item.speaker_name} --data-folder ${item.data_folder}
      outs:
      - ${item.data_folder}/${item.speaker_name}/${item.speaker_name}:
          persist: true
      - ${item.data_folder}/${item.speaker_name}/train_manifest.jsonl:
          persist: true
      - ${item.data_folder}/${item.speaker_name}/val_manifest.jsonl:
          persist: true

  download_pretrained_modules:
    cmd: >-
      python src/download_pretrained.py
      --params-file params.yaml
      --pretrained-dir ${pretrained_models_dir}
    params:
    - pretrained_models_dir
    outs:
    - ${pretrained_models_dir}:
        persist: true

  train_fastpitch:
    foreach: ${speaker}
    do:
      cmd: >-
        python src/train_fastpitch.py
        --config-path configs
        --config-name train_config_fastpitch
        log_dir=${item.log_dir}/fastpitch
        train_manifest=${item.train_manifest_path}
        validation_manifest=${item.val_manifest_path}
        sup_data_path=${item.fastpitch.sup_data_path}
        max_duration=${item.fastpitch.max_dur}
        batch_size=${item.fastpitch.batch_size}
        model.optim.lr=${item.fastpitch.peak_lr}
        trainer.max_epochs=${item.fastpitch.epochs}
        pitch_fmin=${item.fastpitch.pitch_fmin}
        pitch_fmax=${item.fastpitch.pitch_fmax}
        pitch_mean=${item.fastpitch.pitch_mean}
        pitch_std=${item.fastpitch.pitch_std}
        ${item.fastpitch.pretrained_init_arg}
      deps:
      - src/configs/train_config_fastpitch.yaml
      params:
      - speaker.${key}.fastpitch
      outs:
      - ${item.log_dir}/fastpitch
      - ${item.fastpitch.sup_data_path}

  generate_mels:
    foreach: ${speaker}
    do:
      cmd: >-
        python src/generate_mels.py
        --cpu
        --fastpitch-model-ckpt ${item.log_dir}/fastpitch/checkpoints/default.nemo
        --input-json-manifests ${item.train_manifest_path} ${item.val_manifest_path}
        --output-json-manifest-root ${item.data_folder}/${item.speaker_name}/mel_manifests
      deps:
      - ${item.log_dir}/fastpitch
      - ${item.train_manifest_path}
      - ${item.val_manifest_path}
      params:
      - speaker.${key}.log_dir
      - speaker.${key}.train_manifest_path
      - speaker.${key}.val_manifest_path
      outs:
      - ${item.data_folder}/${item.speaker_name}/mel_manifests/train_manifest_mel.jsonl
      - ${item.data_folder}/${item.speaker_name}/mel_manifests/val_manifest_mel.jsonl
      - ${item.data_folder}/${item.speaker_name}/mel_manifests/mels

  train_hifigan:
    foreach: ${speaker}
    do:
      cmd: >-
        python src/train_hifigan.py
        --config-path configs
        --config-name train_config_hifigan
        train_dataset=${item.data_folder}/${item.speaker_name}/mel_manifests/train_manifest_mel.jsonl
        validation_datasets=${item.data_folder}/${item.speaker_name}/mel_manifests/val_manifest_mel.jsonl
        log_dir=${item.log_dir}/hifigan
        batch_size=${item.hifigan.batch_size}
        model.optim.lr=${item.hifigan.peak_lr}
        trainer.max_epochs=${item.hifigan.epochs}
        train_n_segments=${item.hifigan.n_train_segments}
        ${item.hifigan.pretrained_init_arg}
      params:
      - speaker.${key}.hifigan
      deps:
      - src/configs/train_config_hifigan.yaml
      - ${item.data_folder}/${item.speaker_name}/mel_manifests/train_manifest_mel.jsonl
      - ${item.data_folder}/${item.speaker_name}/mel_manifests/val_manifest_mel.jsonl
      - ${item.data_folder}/${item.speaker_name}/mel_manifests/mels
      outs:
      - ${item.log_dir}/hifigan

  infer_and_compare:
    foreach: ${speaker}
    do:
      cmd: >-
        python src/infer_tts.py
        --fastpitch-model-ckpt ${item.log_dir}/fastpitch/checkpoints/default.nemo
        --hifigan-model-ckpt ${item.log_dir}/hifigan/checkpoints/default.nemo
        --manifests ${item.train_manifest_path}
        --manifests ${item.val_manifest_path}
        --output-dir ${item.log_dir}/inference_comparison
        --nrows ${item.inference_comparison_nrows}
        --device cuda
      deps:
      - ${item.log_dir}/fastpitch/checkpoints/default.nemo
      - ${item.log_dir}/hifigan/checkpoints/default.nemo
      - ${item.train_manifest_path}
      - ${item.val_manifest_path}
      params:
      - speaker.${key}
      outs:
      - ${item.log_dir}/inference_comparison


  export_onnx:
    foreach: ${speaker}
    do:
      cmd: >-
        python src/export.py
        --model-type tts
        --pretrained-path ${item.log_dir}/fastpitch/checkpoints/default.nemo
        --target-path ${item.log_dir}/onnx/fastpitch.onnx
        --quantization ${item.export_quantization}
        &&
        python src/export.py
        --model-type hifigan
        --pretrained-path ${item.log_dir}/hifigan/checkpoints/default.nemo
        --target-path ${item.log_dir}/onnx/hifigan.onnx
        --quantization ${item.export_quantization}
      deps:
      - ${item.log_dir}/fastpitch/checkpoints/default.nemo
      - ${item.log_dir}/hifigan/checkpoints/default.nemo
      params:
      - speaker.${key}.export_quantization
      outs:
      - ${item.log_dir}/onnx/fastpitch.onnx
      - ${item.log_dir}/onnx/hifigan.onnx

  infer_onnx:
    foreach: ${speaker}
    do:
      cmd: >-
        python src/infer_onnx.py
        --fastpitch-onnx ${item.log_dir}/onnx/fastpitch.onnx
        --hifigan-onnx ${item.log_dir}/onnx/hifigan.onnx
        --tokenizer-config src/configs/train_config_fastpitch.yaml
        --manifests ${item.train_manifest_path}
        --manifests ${item.val_manifest_path}
        --output-dir ${item.log_dir}/onnx_inference_comparison
        --nrows ${item.inference_comparison_nrows}
      deps:
      - ${item.log_dir}/onnx/fastpitch.onnx
      - ${item.log_dir}/onnx/hifigan.onnx
      - ${item.train_manifest_path}
      - ${item.val_manifest_path}
      - src/configs/train_config_fastpitch.yaml
      params:
      - speaker.${key}.inference_comparison_nrows
      outs:
      - ${item.log_dir}/onnx_inference_comparison


  export_torchaot:
    foreach: ${speaker}
    do:
      cmd: >-
        python src/export_torch_inductor.py
        --model-type tts
        --pretrained-path ${item.log_dir}/fastpitch/checkpoints/default.nemo
        --target-dir ${item.log_dir}/aot_package
        &&
        python src/export_torch_inductor.py
        --model-type hifigan
        --pretrained-path ${item.log_dir}/hifigan/checkpoints/default.nemo
        --target-dir ${item.log_dir}/aot_package
      deps:
      - ${item.log_dir}/fastpitch/checkpoints/default.nemo
      - ${item.log_dir}/hifigan/checkpoints/default.nemo
      params:
      - speaker.${key}
      outs:
      - ${item.log_dir}/aot_package/fastpitch_encoder.pt2
      - ${item.log_dir}/aot_package/fastpitch_decoder.pt2
      - ${item.log_dir}/aot_package/hifigan.pt2
      - ${item.log_dir}/aot_package/fastpitch_encoder_uncompiled.pt2
      - ${item.log_dir}/aot_package/fastpitch_decoder_uncompiled.pt2
      - ${item.log_dir}/aot_package/hifigan_uncompiled.pt2
