speaker:
  caromopfen:
    speaker_name: caromopfen
    data_folder: data
    log_dir: trained_pipelines/caro
    inference_comparison_nrows: 10
    export_quantization: "QInt8"
    train_manifest_path: data/caromopfen/train_manifest.jsonl
    val_manifest_path: data/caromopfen/val_manifest.jsonl
    fastpitch:
      sup_data_path: data/caromopfen/fastpitch_sup_data
      max_dur: 13
      batch_size: 16
      peak_lr: 0.0001
      epochs: 100
      pretrained_init_arg: "+init_from_nemo_model=pretrained_models/FemaleFastpitchHUI_44100.nemo"  # Set to "" for training from scratch
      val_batch_size: 16
      val_max_dur: 13
    hifigan:
      pretrained_init_arg: "+init_from_pretrained_model._.name=tts_de_hui_hifigan_ft_fastpitch_multispeaker_5"  # Set to "++init_from_nemo_model=/path/to/model.nemo" or "" when needed
      batch_size: 8
      peak_lr: 0.0001
      epochs: 25
      n_train_segments: 51200
      val_batch_size: 8
      val_n_segments: 131072
      val_max_duration: 30
      val_min_duration: 3

  Karlsson:
    speaker_name: Karlsson
    data_folder: data
    log_dir: trained_pipelines/Karlsson
    inference_comparison_nrows: 10
    export_quantization: "QInt8"
    train_manifest_path: data/Karlsson/train_manifest.jsonl
    val_manifest_path: data/Karlsson/val_manifest.jsonl
    fastpitch:
      sup_data_path: data/Karlsson/fastpitch_sup_data
      max_dur: 13
      batch_size: 16
      peak_lr: 0.0001
      epochs: 50
      pretrained_init_arg: "+init_from_pretrained_model._.name=tts_de_fastpitch_multispeaker_5 +init_from_pretrained_model._.exclude=['fastpitch.encoder.word_emb.weight']"  # Set to "" for training from scratch
      val_batch_size: 16
      val_max_dur: 13

    hifigan:
      pretrained_init_arg: "+init_from_pretrained_model._.name=tts_de_hui_hifigan_ft_fastpitch_multispeaker_5"
      batch_size: 8
      peak_lr: 0.0001
      epochs: 10
      n_train_segments: 51200
      val_batch_size: 8
      val_n_segments: 131072
      val_max_duration: 30
      val_min_duration: 3

pretrained_models_dir: pretrained_models
pretrained_downloads:
  - FemaleFastpitchHUI_44100.nemo
