caro: 
  train_manifest_path: ../data/caromopfen/train_manifest.jsonl
  val_manifest_path: ../data/caromopfen/val_manifest.jsonl
  sup_data_path: ../data/caromopfen/fastpitch_sup_data
  fastpitch_pretrained_init_arg: "+init_from_nemo_model=../pretrained_models/FemaleFastpitchHUI_44100.nemo"  # Set to "" for training from scratch
  fastpitch_max_dur: 13
  fastpitch_batch_size: 16
  fastpitch_peak_lr: 1e-4
  fastpitch_epochs: 50
  speaker_name: caromopfen
  data_folder: ../data
  log_dir: ../trained_pipelines/caro
  hifigan_pretrained_init_arg: "+init_from_pretrained_model._.name=tts_de_hui_hifigan_ft_fastpitch_multispeaker_5"  # Set to "++init_from_nemo_model=/path/to/model.nemo" or "" when needed
  hifigan_batch_size: 24
  hifigan_epochs: 5
  hifigan_peak_lr: 1e-4
  hifigan_n_train_segments: 16384
  inference_comparison_nrows: 20